[package]
name = "proxy"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
anyhow = "1.0.75"
argh = "0.1.12"
colored = "2.0.4"
imap-codec = { version = "1.0.0", features = ["bounded-static", "quirk_crlf_relaxed"] }
imap-flow = { path = ".." }
rustls = "0.21.7"
rustls-pemfile = "2.0.0-alpha.1"
serde = { version = "1.0.171", features = ["derive"] }
thiserror = "1.0.49"
tokio = { version = "1.28", features = ["full"] }
tokio-rustls = "0.24.1"
toml = "0.8.2"
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.17", features = ["env-filter"] }
webpki-roots = "0.25.2"
